name: Run Fetch JSON

on: 
push:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-versions: "3.12"
          cache: "pip"

      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Script
        env:
          TARGET_URL: "None"
        run: |
          python fetch_json.py


